---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-acme
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgCRR90d4G0/fqDjDLZex/2RWC8B5rr+3eJuMWOU58eR5GejVUSD0m1hbF4F+nEpcVoT5fpdDKneJlT428mQgQm5hevX0rsoziVG8g2wCl7EuRjilwNPNF0JInyfWJJLUSfKUkPAKNyWmNGeOc2NxOFnH2HWKizxw+XHI7OI/y2hRoIUdl9F5/nCJMGuMYjHgpAdEBa31GZTTLkVKhQu2V0jFm6YOHOFeKAOY62nmm/36iMlxxxarZUMc20xLWpVmzK5LNPMVe7inplEjuQY+GVhn71Ts1L9UqMRDgepqbiCVyockZaGKNBq53U4s1sG6l8cg5zZsVLmv1CQnAGmgNyiueX1S9eRpTRCtksB8wxen9qoHqo1bFzzr0TpGRKoLxoki+lXaM02b2mhkRsfmPuPIlnu8HVZu0xjENy+sgJGSKVVE4tUaM1V9BwsC0eofzpP5zhIUUFAEadVGqcX7eLLjljL4mx/KFUf/AIwbqtwsh6TK4EITpSFv0O5m+ElWRqFudgL5IGCQmJonrfXNxZS/zRcapyiycK+cT9wqWFpvvHijO9PixgJSrrhbz+Mkkiw8bP2dv3eA6PfundevB8vFzwICtXH7RZJgKHPXiVs4axrnvlwq0vPspe2u+3Ef/hB7DNTyEWglpIGkLCl8N+XqFEDFPPgdxQez4g3iSHCAl8486/gWr373cmhojnrqnUkAd2MartIFBZaayucWHiDrnZLkvotNvL28/UZzOXYbhPuTcOgxE36wkGdCqXKujo2yEkgrA==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-acme
      namespace: kube-system
