apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`lucasrocha.dpdns.org`) && PathPrefix(`/jellyfin`)
      kind: Rule
      middlewares:
        - name: strip-jellyfin
        - name: https-proto
      services:
        - name: jellyfin
          port: 8096
