apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:apache
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
          env:
            - name: NEXTCLOUD_DATA_DIR
              value: /var/www/html/data
            - name: NEXTCLOUD_HOST
              value: "localhost"
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "192.168.0.100"
            - name: PHP_VALUE
              value: "auto_preload_file=null"
            - name: OVERWRITEWEBROOT
              value: "/nextcloud"
            - name: OVERWRITEHOST
              value: "192.168.0.100"
            - name: DATABASE_TYPE
              value: mysql
            - name: DATABASE_HOST
              value: mariadb
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: database
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data