---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-tunnel
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAaDQZ3/gkGUInYDenVgsTlpbJYJj8MIuG8kmxkGaGa6yUmKFb1CUWWew7jp3GWM71BclKGJTYdjKVf/EbQ8OOR9nZaL4tLYwSLh5v2vs/0aXO3cawRluuDMLJjjbloSOIke5B/fnYqgXpWI8bOgLrpoweqb7BQDTo4jUcpToeHW4otxppPv+a2jY0RAgRVle9Q0RQ+JekgWb3A0EM0CG8pi4VSd3asqNIQJd4GCuGsceA5DXC+FrL8cRXK5X+AVrOkZnZdmPrlKd6IrVtPDrT+EITPKI5x2vQl7Ld7J2vIojOYTU91UcOZi6lz15+h5YTWCmTbrHm/kS3MFz5TlLChTMypfrmQfk5tFb7DfxedC5Ejz2Agn9awBXYgTyX94DX0uk7lAIqAf6P0nz+Qp9XBYZLk+bE6Ua+6lxSVJpoM6qr0XPsIXNp3wskcCFEQUWubtT/wwkiZWu24sIGuC22IsmdCoSHcU1Y3ZOVsF7Vm3TK84zwLeCsTpwTvv2HuyyMGtC6v5qJC5NR9oGtITj6dwrhWmi6Hj/83sJYjyHY0+JyHhJg11OUiNclxCe3LoVvhma8UpJqlBZ5nUD47oQ6I+jjS3Rk3rLlp89Xm6HmPV0EM0/7c4EEm5Sb4D8riJ7wpvgPQF6GA7F82gbsXeLvg+6aM6Jntmrv/LPu3u3BIWXN30j2mHt/Zj15xEdiF3qPC36t9N1PMDY3fhojj2nDH6zHpSEI9wWf1zLnsiEPfL6PdsqiXFbR2haKhSDju9ifQTPSGti9BdZ8jw+6QkTCJ8jfi0otmCGdkuQn7PPktIM/syEeheH0RcwIH/CiaXrjZud9iDYRCy2v5RMIqEwlyNw7KY3t4pTMId6LhrYabkzGysyryoa7cRqYDSt4fBhMyWfHiJ85UPTcGIcVkYPqt7F2EVTwCdR13nmsspjkbr54r0k9QoiGL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-tunnel
      namespace: cloudflared
