apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:1.68.0
          ports:
            - containerPort: 5678
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
          env:
            - name: WEBHOOK_URL
              value: "http://192.168.0.100/n8n"
            - name: N8N_BASE_URL
              value: "http://192.168.0.100/n8n"
            - name: N8N_PROTOCOL
              value: "http"
            - name: GENERIC_TIMEZONE
              value: "America/Sao_Paulo"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "false"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data