apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  namespace: n8n
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`lucasrocha.dpdns.org`) && PathPrefix(`/n8n`)
      kind: Rule
      middlewares:
        - name: strip-n8n
        - name: https-proto
      services:
        - name: n8n
          port: 5678
