apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: n8n
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.replace-path: /n8n$2
spec:
  rules:
  - http:
      paths:
      - path: /n8n(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: n8n
            port:
              number: 5678